"""initial schema (Milestone 1)

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-10

This baseline creates every M1 table from the SQLAlchemy metadata. Subsequent
milestones add incremental, autogenerated migrations on top.
"""

from __future__ import annotations

from alembic import op

from app.db import Base
from app import models  # noqa: F401

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
