"""m2 assets asset_sources asset_edges

Revision ID: 0002_m2_assets
Revises: 0001_initial
Create Date: 2026-09-10 17:36:29.203315
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002_m2_assets'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('domain', 'subdomain', 'ip', 'url', name='assettype'), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('in_scope', sa.Boolean(), nullable=False),
    sa.Column('scope_reason', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('unknown', 'resolved', 'alive', 'dead', name='assetstatus'), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('ip_addresses', sa.JSON(), nullable=False),
    sa.Column('cname', sa.String(length=300), nullable=False),
    sa.Column('asn', sa.String(length=32), nullable=False),
    sa.Column('is_wildcard', sa.Boolean(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('http_title', sa.String(length=500), nullable=False),
    sa.Column('http_server', sa.String(length=200), nullable=False),
    sa.Column('http_scheme', sa.String(length=10), nullable=False),
    sa.Column('http_port', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('final_url', sa.String(length=1000), nullable=False),
    sa.Column('tls_names', sa.JSON(), nullable=False),
    sa.Column('technologies', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_seen_scan', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['first_seen_scan'], ['scan_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'type', 'value', name='uq_asset_project_type_value')
    )
    op.create_index(op.f('ix_assets_in_scope'), 'assets', ['in_scope'], unique=False)
    op.create_index(op.f('ix_assets_org_id'), 'assets', ['org_id'], unique=False)
    op.create_index(op.f('ix_assets_project_id'), 'assets', ['project_id'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_index(op.f('ix_assets_type'), 'assets', ['type'], unique=False)
    op.create_index(op.f('ix_assets_value'), 'assets', ['value'], unique=False)
    op.create_table('asset_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('src_asset_id', sa.Uuid(), nullable=False),
    sa.Column('dst_asset_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('resolves_to', 'cname_to', 'redirects_to', 'hosts', name='edgekind'), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dst_asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src_asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('src_asset_id', 'dst_asset_id', 'kind', name='uq_edge')
    )
    op.create_index(op.f('ix_asset_edges_dst_asset_id'), 'asset_edges', ['dst_asset_id'], unique=False)
    op.create_index(op.f('ix_asset_edges_project_id'), 'asset_edges', ['project_id'], unique=False)
    op.create_index(op.f('ix_asset_edges_src_asset_id'), 'asset_edges', ['src_asset_id'], unique=False)
    op.create_table('asset_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('detail', sa.String(length=300), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'source', name='uq_asset_source')
    )
    op.create_index(op.f('ix_asset_sources_asset_id'), 'asset_sources', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_sources_asset_id'), table_name='asset_sources')
    op.drop_table('asset_sources')
    op.drop_index(op.f('ix_asset_edges_src_asset_id'), table_name='asset_edges')
    op.drop_index(op.f('ix_asset_edges_project_id'), table_name='asset_edges')
    op.drop_index(op.f('ix_asset_edges_dst_asset_id'), table_name='asset_edges')
    op.drop_table('asset_edges')
    op.drop_index(op.f('ix_assets_value'), table_name='assets')
    op.drop_index(op.f('ix_assets_type'), table_name='assets')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_project_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_org_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_in_scope'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
