"""m3 infra vhosts endpoints

Revision ID: 0003_m3_infra_vhosts_endpoints
Revises: 0002_m2_assets
Create Date: 2026-09-10 18:16:22.654641
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003_m3_infra_vhosts_endpoints'
down_revision: Union[str, None] = '0002_m2_assets'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vhosts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('hostname', sa.String(length=300), nullable=False),
    sa.Column('scheme', sa.String(length=10), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('classification', sa.Enum('default', 'interesting', 'potential_internal', 'unusual_response', name='vhostclass'), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_bytes', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('server', sa.String(length=200), nullable=False),
    sa.Column('baseline_status', sa.Integer(), nullable=True),
    sa.Column('baseline_bytes', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('in_scope', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'ip', 'hostname', name='uq_vhost')
    )
    op.create_index(op.f('ix_vhosts_classification'), 'vhosts', ['classification'], unique=False)
    op.create_index(op.f('ix_vhosts_hostname'), 'vhosts', ['hostname'], unique=False)
    op.create_index(op.f('ix_vhosts_ip'), 'vhosts', ['ip'], unique=False)
    op.create_index(op.f('ix_vhosts_org_id'), 'vhosts', ['org_id'], unique=False)
    op.create_index(op.f('ix_vhosts_project_id'), 'vhosts', ['project_id'], unique=False)
    op.create_table('endpoints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('host', sa.String(length=300), nullable=False),
    sa.Column('scheme', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('normalized_url', sa.String(length=1200), nullable=False),
    sa.Column('sample_url', sa.String(length=2000), nullable=False),
    sa.Column('query_keys', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('in_scope', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_seen_scan', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['first_seen_scan'], ['scan_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'method', 'normalized_url', name='uq_endpoint_project_method_norm')
    )
    op.create_index(op.f('ix_endpoints_asset_id'), 'endpoints', ['asset_id'], unique=False)
    op.create_index(op.f('ix_endpoints_host'), 'endpoints', ['host'], unique=False)
    op.create_index(op.f('ix_endpoints_in_scope'), 'endpoints', ['in_scope'], unique=False)
    op.create_index(op.f('ix_endpoints_normalized_url'), 'endpoints', ['normalized_url'], unique=False)
    op.create_index(op.f('ix_endpoints_org_id'), 'endpoints', ['org_id'], unique=False)
    op.create_index(op.f('ix_endpoints_project_id'), 'endpoints', ['project_id'], unique=False)
    for col, length in (("ptr", 300), ("netblock", 64), ("asn_org", 200),
                        ("cloud_provider", 60), ("geo_country", 4)):
        op.add_column(
            "assets",
            sa.Column(col, sa.String(length=length), nullable=False, server_default=""),
        )

    # New enum values (Postgres native enums need an explicit ALTER TYPE).
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for val in ("asn", "netblock"):
            op.execute(f"ALTER TYPE assettype ADD VALUE IF NOT EXISTS '{val}'")
        for val in ("belongs_to", "announced_by", "serves"):
            op.execute(f"ALTER TYPE edgekind ADD VALUE IF NOT EXISTS '{val}'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'geo_country')
    op.drop_column('assets', 'cloud_provider')
    op.drop_column('assets', 'asn_org')
    op.drop_column('assets', 'netblock')
    op.drop_column('assets', 'ptr')
    op.drop_index(op.f('ix_endpoints_project_id'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_org_id'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_normalized_url'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_in_scope'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_host'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_asset_id'), table_name='endpoints')
    op.drop_table('endpoints')
    op.drop_index(op.f('ix_vhosts_project_id'), table_name='vhosts')
    op.drop_index(op.f('ix_vhosts_org_id'), table_name='vhosts')
    op.drop_index(op.f('ix_vhosts_ip'), table_name='vhosts')
    op.drop_index(op.f('ix_vhosts_hostname'), table_name='vhosts')
    op.drop_index(op.f('ix_vhosts_classification'), table_name='vhosts')
    op.drop_table('vhosts')
    # ### end Alembic commands ###
