"""Static catalog of the built-in tool plugins.

Mirrors orchestrator/internal/tools/registry.go so the Tool Manager UI can list
every tool (with docs, capabilities, safety class) before the first health
check has run. The orchestrator remains the source of truth for installed
versions and health.
"""

from __future__ import annotations

CATALOG: list[dict] = [
    {
        "name": "subfinder",
        "display_name": "Subfinder",
        "homepage": "https://github.com/projectdiscovery/subfinder",
        "docs": "https://docs.projectdiscovery.io/tools/subfinder",
        "capabilities": ["subdomain_enum"],
        "safety_class": "passive",
        "needs_api_key": False,
        "min_version": "2.6.0",
        "tested_version": "2.16.0",
        "install_hint": "go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest",
    },
    {
        "name": "dnsx",
        "display_name": "DNSX",
        "homepage": "https://github.com/projectdiscovery/dnsx",
        "docs": "https://docs.projectdiscovery.io/tools/dnsx",
        "capabilities": ["dns_resolve"],
        "safety_class": "low",
        "needs_api_key": False,
        "min_version": "1.2.0",
        "tested_version": "1.3.1",
        "install_hint": "go install -v github.com/projectdiscovery/dnsx/cmd/dnsx@latest",
    },
    {
        "name": "httpx",
        "display_name": "HTTPX",
        "homepage": "https://github.com/projectdiscovery/httpx",
        "docs": "https://docs.projectdiscovery.io/tools/httpx",
        "capabilities": ["http_probe"],
        "safety_class": "low",
        "needs_api_key": False,
        "min_version": "1.3.0",
        "tested_version": "1.11.0",
        "install_hint": "go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest",
    },
    {
        "name": "katana",
        "display_name": "Katana",
        "homepage": "https://github.com/projectdiscovery/katana",
        "docs": "https://docs.projectdiscovery.io/tools/katana",
        "capabilities": ["crawl"],
        "safety_class": "active",
        "needs_api_key": False,
        "min_version": "1.0.0",
        "tested_version": "1.7.0",
        "install_hint": "go install -v github.com/projectdiscovery/katana/cmd/katana@latest",
    },
    {
        "name": "gau",
        "display_name": "gau (GetAllUrls)",
        "homepage": "https://github.com/lc/gau",
        "docs": "https://github.com/lc/gau",
        "capabilities": ["historical_urls"],
        "safety_class": "passive",
        "needs_api_key": False,
        "min_version": "2.0.0",
        "tested_version": "2.2.4",
        "install_hint": "go install github.com/lc/gau/v2/cmd/gau@latest",
    },
    {
        "name": "assetfinder",
        "display_name": "assetfinder",
        "homepage": "https://github.com/tomnomnom/assetfinder",
        "docs": "https://github.com/tomnomnom/assetfinder",
        "capabilities": ["subdomain_enum"],
        "safety_class": "passive",
        "needs_api_key": False,
        "min_version": "0.1.0",
        "tested_version": "0.1.1",
        "install_hint": "go install github.com/tomnomnom/assetfinder@latest",
    },
    {
        "name": "nuclei",
        "display_name": "Nuclei",
        "homepage": "https://github.com/projectdiscovery/nuclei",
        "docs": "https://docs.projectdiscovery.io/tools/nuclei",
        "capabilities": ["vuln_scan"],
        "safety_class": "active",
        "needs_api_key": False,
        "min_version": "3.0.0",
        "tested_version": "3.11.1",
        "install_hint": "go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest",
    },
    {
        "name": "naabu",
        "display_name": "Naabu",
        "homepage": "https://github.com/projectdiscovery/naabu",
        "docs": "https://docs.projectdiscovery.io/tools/naabu",
        "capabilities": ["port_scan"],
        "safety_class": "active",
        "needs_api_key": False,
        "min_version": "2.1.0",
        "tested_version": "2.6.1",
        "install_hint": "go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest",
    },
    {
        "name": "ffuf",
        "display_name": "ffuf",
        "homepage": "https://github.com/ffuf/ffuf",
        "docs": "https://github.com/ffuf/ffuf/wiki",
        "capabilities": ["content_discovery"],
        "safety_class": "active",
        "needs_api_key": False,
        "min_version": "2.0.0",
        "tested_version": "2.1.0",
        "install_hint": "go install github.com/ffuf/ffuf/v2@latest",
    },
    {
        "name": "trufflehog",
        "display_name": "TruffleHog",
        "homepage": "https://github.com/trufflesecurity/trufflehog",
        "docs": "https://github.com/trufflesecurity/trufflehog",
        "capabilities": ["secret_scan"],
        "safety_class": "passive",
        "needs_api_key": False,
        "min_version": "3.60.0",
        "tested_version": "3.97.4",
        "install_hint": "curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh",
    },
    {
        "name": "gitleaks",
        "display_name": "Gitleaks",
        "homepage": "https://github.com/gitleaks/gitleaks",
        "docs": "https://github.com/gitleaks/gitleaks",
        "capabilities": ["secret_scan"],
        "safety_class": "passive",
        "needs_api_key": False,
        "min_version": "8.0.0",
        "tested_version": "8.30.1",
        "install_hint": "download from https://github.com/gitleaks/gitleaks/releases",
    },
    {
        "name": "nmap",
        "display_name": "Nmap",
        "homepage": "https://nmap.org",
        "docs": "https://nmap.org/book/man.html",
        "capabilities": ["port_scan"],
        "safety_class": "active",
        "needs_api_key": False,
        "min_version": "7.0.0",
        "tested_version": "7.98",
        "install_hint": "apt-get install nmap  (or https://nmap.org/download.html)",
    },
]

BY_NAME = {t["name"]: t for t in CATALOG}
