apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argus.fullname" . }}-config
  labels: {{- include "argus.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- if not .Values.secrets.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argus.fullname" . }}-secrets
  labels: {{- include "argus.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.data }}
  {{- if $v }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
{{- end }}
